name = "crm"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
SQUARE_ENVIRONMENT = "production"
SQUARE_DEFAULT_LOCATION_ID = "LN4WBHANNNZ2Y"
